stages:
  - tarball
  - build

before_script:
  - ci/version.sh
  - lfortran_version=$(<version)

prepare tarball:
  stage: tarball
  image: registry.gitlab.com/lfortran/ci-images:prepare-1.7.0
  script:
    - export CLASSPATH="$HOME/antlr-4.7-complete.jar:$CLASSPATH"
    - ./build0.sh
    - python setup.py sdist
    - ci/upload_tarball.sh
  artifacts:
    paths:
      - dist/*
    when: always
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.com/lfortran/packages/testing/tree/$CI_COMMIT_REF_NAME

# GitHub mirror
mirror:
  stage: tarball
  image: registry.gitlab.com/lfortran/ci-images:mirror-1.7.0
  script:
    - ci/github_mirror.sh
  allow_failure: true
  only:
    - master

# PyPI upload
pypi:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:prepare-1.7.0
  script:
    - sudo apk add gcc python3-dev musl-dev libffi-dev openssl-dev
    - sudo pip install twine
    - ci/upload_pypi.sh
  #only:
  #  - master
  #  - tags

# Azure
azure:
  stage: tarball
  image: registry.gitlab.com/lfortran/ci-images:mirror-1.7.0
  script:
    - ci/azure_mirror.sh
  only:
    variables:
      - $SSH_PRIVATE_KEY_AZURE


# Test full dependencies when a C compiler is available and used for linking
full:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:full-1.7.0
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - conda install -c conda-forge python-clang
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - pip install --no-index -v .
    - cd ..
    - rm -r lfortran lfortran-${lfortran_version}
    - rm lfort
    - py.test --pyargs lfortran
    - python show_ast.py
    - lfort examples/expr2.f90 -o a.out
    - ./a.out
    - ./test_lfort_cmdline gfortran
    - ./test_lfort_cmdline lfort
    - ./test_lfort gfortran
    - ./test_lfort lfort
    - cd old_tests/interop
    - ./run.sh

# Test the C++ version
cxx:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:full-1.7.0
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - conda install -c conda-forge rapidjson
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - cmake
         -DCMAKE_PREFIX_PATH=$HOME/conda_root
         -DCMAKE_INSTALL_PREFIX=`pwd`
         -DCMAKE_BUILD_TYPE=Debug
         -DWITH_JSON=yes
         .
    - cmake --build . --target install
    - ctest --output-on-failure
    - ./src/bin/parse

# Create a binary tarball with the C++ based LFortran
cxx_binary:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:cxxbinary-1.8.0
  script:
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - cmake
         -DCMAKE_BUILD_TYPE=Release
         -DWITH_LLVM=yes
         -DLFORTRAN_STATIC_BIN=yes
         .
    - make
    - ctest --output-on-failure
    - cpack
  artifacts:
    paths:
      - lfortran-*/lfortran-*-Linux.tar.bz2
    when: always

# Test the multiplatform build script
build.xsh:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:full2-1.7.0
  script:
    - export CONDA_PREFIX="$HOME/conda_root"
    - export PATH="$HOME/conda_root/bin:$PATH"
    - sudo apt-get update
    - sudo apt-get install -yq --no-install-recommends zlib1g-dev
    - conda install -c conda-forge llvmdev=9.0.1 toml
    - export LFORTRAN_CMAKE_GENERATOR="Unix Makefiles"
    - export WIN=0
    - export MACOS=0
    - xonsh ci/build.xsh

# Build and upload documentation
documentation:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:jupyter-1.7.0
  script:
    - sudo apt-get update
    - sudo apt-get install -yq --no-install-recommends openssh-client
    - export PATH="$HOME/conda_root/bin:$PATH"
    - pip install nbconvert mkdocs
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - pip install --no-index -v .
    - cd ..
    - rm -r lfortran lfortran-${lfortran_version}
    - cd doc
    - python convert_nb.py
    - mkdocs build -s
    - ../ci/upload_docs.sh
  artifacts:
    paths:
      - doc/site
    when: always

# Update the downloads page
downloads_update:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:prepare-1.8.0
  script:
    - curl -X POST -F token=${DOWNLOAD_UPDATE_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/11905898/trigger/pipeline
  only:
    - master

# Test minimal dependencies needed to get things to run. No gcc or clang
# compilers, just the linker `ld` and the musl C library.
minimal:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:minimal-1.7.0
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - export CFLAGS="-I/usr/include/x86_64-linux-musl/"
    - pip install --no-index -v .
    - cd ..
    - rm -r lfortran lfortran-${lfortran_version}
    - rm lfort
    - sudo apt-get remove -yq gcc g++ libc6-dev
    - sudo apt-get autoremove -yq
    - py.test --pyargs lfortran
    - lfort --ld-musl examples/expr2.f90 -o a.out
    - ./a.out

# Test Jupyter notebooks
jupyter:
  stage: build
  image: registry.gitlab.com/lfortran/ci-images:jupyter-1.7.0
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - tar xzf dist/lfortran-${lfortran_version}.tar.gz
    - cd lfortran-${lfortran_version}
    - pip install --no-index -v .
    - cd ..
    - rm -r lfortran lfortran-${lfortran_version}
    - (git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/lfortran/fortran_kernel && cd fortran_kernel && git checkout v0.1.4 && pip install --no-index . && cd .. && rm -r fortran_kernel)
    - python -m fortran_kernel.install --sys-prefix
    - jupyter kernelspec list --json
    - cd share/lfortran/nb
    - py.test --pyargs lfortran
    - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output Demo_out.ipynb Demo.ipynb
    - ls -l output1.png
  artifacts:
    paths:
      - share/lfortran/nb/Demo_out.ipynb
      - share/lfortran/nb/output1.png
    when: always
