name: lp
channels:
  - conda-forge
dependencies:
  - git
  - pip
  - make
  - re2c
  - toml
  - zlib
  - cmake
  - numpy
  - flake8
  - setuptools
  - bison=3.4
  - python=3.10.2
  - llvmdev=16.0.6
  - zstd-static=1.5.5
