site_name: LFortran Documentation

nav:
    - Home: index.md
    - installation.md
    - language.md
    - progress.md
    - Developer's Guide:
        - design.md
        - developer_tutorial.md
        - AST and ASR.md
        - CONTRIBUTING.md

# Until https://gitlab.com/lfortran/lfortran/issues/89 is fixed, we disable the
# "Edit on GitLab" link:
#repo_url: https://gitlab.com/lfortran/lfortran
#edit_uri: blob/master/doc/src

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
    - ansi.css

theme:
    name: material
    palette:
      primary: orange
    highlightjs: true
    hljs_languages:
        - fortran

docs_dir: src
