name: lp
channels:
  - conda-forge
  - defaults
dependencies:
  - llvmdev=11.1.0
  - toml=0.10.2
  - pytest=7.2.0
  - jupyter=1.0.0
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test=0.4.4
  - xonsh=0.13.3
  - re2c=2.2
  - numpy=1.23.4
  - zlib
  - zstd
  - ninja=1.11.0
  - rapidjson=1.1.0
#  - bison=3.4  [not win]
#  - m2-bison=3.4  [win]
